# .readthedocs.yml

build:
  image: latest

python:
  version: 3.6
  setup_py_install: true

# Don't build any extra formats
formats: []

requirements_file: requirements.txt

conda:
  file: environment.yml
