name: Check Ruff formatting and linting

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    if: github.repository == 'PSLmodels/OG-Core'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v7
      - name: Check formatting with Ruff
        run: uvx ruff format --check .
      - name: Check linting with Ruff
        run: uvx ruff check .
